Fix sse-enabled build
Build both with -msse and -Werror causes

   cc1: all warnings being treated as errors
   dl-runtime.c:1:0: error: SSE instruction set disabled, using 387 arithmetics [-Werror]

Change-Id: I4f62d652d12dd5b611e2ea51b03601abd2234385
Signed-off-by: Vyacheslav Barinov <v.barinov@samsung.com>